{% set name = "dvc-data" %}
{% set version = "0.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3385054422b66738948690d96944bc547f2f26edfa5776bc0c0a4f9f64a8cc42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - funcy >=1.14
    - dictdiffer >=0.8.1
    - pygtrie >=2.3.2
    - shortuuid >=0.5.0
    - dvc-objects ==0.14.1
    - nanotime >=0.5.2
    - diskcache >=5.2.1
    - attrs >=21.3.0

test:
  imports:
    - dvc_data
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-data
  summary: DVC data management library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - pmrowla
    - shcheklein
    - skshetry
